# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  	desc "Description of what the lane does"
  	lane :beta do
    increment_build_number
    match(
    	git_url: "https://gitee.com/wang1990.com/iosProvingProfile.git",
    	type: "development" ,#can be appstore,adhoc, development,enterprise
    	app_identifier:"com.youhong.fastlaneDemo",
    	username:"283175161@qq.com",
    	readonly: true
    	)
    # 编译代码
    gym(
    	scheme:"fastlaneDemo",
    	export_method:"development",
    	output_directory:"./build",
    	archive_path:"./Archive",       
    	)
    tests
    firim(firim_api_token: "ed1421ff86837b720a7053684b934147")
  	end


	lane :release do
  	  # 增加build版本号
  	increment_build_number
  	match(
    	git_url: "https://gitee.com/wang1990.com/iosProvingProfile.git",
    	type: "appstore" ,#can be appstore,adhoc, development,enterprise
    	app_identifier:"com.youhong.fastlaneDemo",
    	username:"283175161@qq.com",
    	readonly: true
    	)
  	# 编译代码
    gym(
    	scheme:"fastlaneDemo",
    	export_method:"app-store"
    	)
    # 发布到Apple Store
    deliver(
    	username:"283175161@qq.com",
      	skip_screenshots:true,
      	force:true,
      	submit_for_review:true,
    	)
  	end

  	# 添加测试Unit Test 
	lane :tests do
	run_tests(scheme: "fastlaneDemoTests")
	end
  
end
